version: '3'

services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-4-prerelease-20210513
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-4-prerelease-20210513
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  nestjs:
    build:
      context: ./aurora-backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      TZ: 'Asia/Seoul'
      PORT: 80
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: dbName
      DB_USER: user
      DB_PASSSWORD: userPassword
      PRIVATE_KEY: ""
      SELENIUM_SERVER: "http://localhost:4444"
      DESKTOP_NAME: "PURORA-GIT-SERVER"
      DEVICE_UUID: ""
      KAKAO_ID: ""
      KAKAO_PW: ""

    ports:
      - 80:80
    depends_on:
      - database
    links:
      - database:database
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
    restart: always

  database:
    image: mysql:8
    command:
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_unicode_ci
     - --default-authentication-plugin=mysql_native_password
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: dbName
      MYSQL_USER: user
      MYSQL_PASSWORD: userPassword
      TZ: 'Asia/Seoul'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
