# This is a basic workflow that is manually triggered

name: CI

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - name: Run a on-line script
      run: echo "Hello ${{ github.event.inputs.name }}"
