name: MAIN CI

on:
  push:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-18.04
  
    steps:
    - name: git clone #
      uses: actions/checkout@v2
      
    - name: npm install #
      run: |
        cd purora-frontend \
        npm install
        
    - name: build #
      run: npm run build:prod
      
    - name: deploy
      env:
        AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      run: |
        aws s3 cp \
        --recursive \
        --region ap-northeast-2 \
        dist s3://purora
